### ISSUE TITLE
Figure 2 Input file not available.

### ISSUE THREAD

**Issue by pablasimarjot** [kevlitchfield1/CPI1000_paper#1]
Input file "meta_analysis_input_data.txt" not included in the repo.

Error in file(file, "rt") : cannot open the connection
In addition: Warning message:
In file(file, "rt") :
  cannot open file './meta_analysis_input_data.txt': No such file or directory

**Comment by kevlitchfield1** [comment]
Thanks for your email Simar, based on our discussion there I'll now mark this as closed
